tniasm ryu.asm
tniasm chunli.asm
tniasm dhalsim.asm
tniasm guile.asm
tniasm ehonda.asm
tniasm cammy.asm
tniasm vega.asm
tniasm blanka.asm
tniasm thawk.asm
tniasm mbison.asm
tniasm deejay.asm
tniasm feilong.asm
tniasm scorpion.asm
tniasm billykane.asm
tniasm haggar.asm
tniasm joehigashi.asm
tniasm damnd.asm
tniasm titanictim.asm
tniasm harmandoelan.asm
tniasm maishiranui.asm
tniasm guy.asm

del ryucharacterface.SC5
del tniasm.sym
del tniasm.tmp
del tniasm.out